name:
  - Thin-Film-Design
channels:
  - conda-forge
dependencies:
  - python=3.9 
  - ipykernel 
  - scipy
  - numpy=1.23 
  - numba=0.56.4
  - matplotlib 
  # You may need to change the following line according the
  # version of the CUDA driver! 
  # CUDA driver version can be found using nvidia-smi.
  - cudatoolkit=11.7 